DEMO_COMPOUNDS = [
    {
        "id": "N3",
        "name": "N3 (crystal structure ligand)",
        "smiles": "CC(=O)OCC(=O)[C@@H]1CCCN1C(=O)[C@@H](NC(=O)[C@H](CC2CCCCC2)NC(=O)[C@@H](NC(=O)c3cnccn3)C(C)(C)C)CC4CC4",
        "known_ki_nm": 34.0,
    },
    {
        "id": "GC376",
        "name": "GC-376",
        "smiles": "O=C(Cn1ccnc1)N[C@@H](CC(=O)OCc1ccccc1)C(=O)N2CCC[C@H]2C(=O)CBr",
        "known_ki_nm": 3.0,
    },
    {
        "id": "nirmatrelvir",
        "name": "Nirmatrelvir (Paxlovid)",
        "smiles": "CC1(C)C[C@@H]1NC(=O)[C@H](F)C(=O)N[C@@H](C#N)C[C@H]1CCNC1=O",
        "known_ki_nm": 3.11,
    },
    {
        "id": "boceprevir",
        "name": "Boceprevir",
        "smiles": "CC(C)(C)NC(=O)[C@@H]1[C@H]2CC[C@@H](C2)CN1C(=O)[C@@H](NC(=O)C(NC(=O)c1cnccn1)C(C)(C)C)C(C)(C)C",
        "known_ki_nm": 4200.0,
    },
    {
        "id": "ebselen",
        "name": "Ebselen",
        "smiles": "O=C1c2ccccc2-n2c1[Se]c1ccccc12",
        "known_ki_nm": 670.0,
    },
    {
        "id": "carmofur",
        "name": "Carmofur",
        "smiles": "CCCCCCNC(=O)N1C=CC(=O)NC1=O",
        "known_ki_nm": 1350.0,
    },
    {
        "id": "tideglusib",
        "name": "Tideglusib",
        "smiles": "O=C1N(Cc2ccccc2)C(=O)/C1=C/c1cccs1",
        "known_ki_nm": 1500.0,
    },
    {
        "id": "shikonin",
        "name": "Shikonin",
        "smiles": "CC(C)=CC[C@H](O)C1=CC(=O)c2c(O)ccc(O)c2C1=O",
        "known_ki_nm": 1290.0,
    },
    {
        "id": "disulfiram",
        "name": "Disulfiram",
        "smiles": "CCN(CC)C(=S)SSC(=S)N(CC)CC",
        "known_ki_nm": 9350.0,
    },
    {
        "id": "PX12",
        "name": "PX-12",
        "smiles": "CCCCCCSSCC",
        "known_ki_nm": 21400.0,
    },
    {
        "id": "TDZD8",
        "name": "TDZD-8",
        "smiles": "O=C1N(Cc2ccccc2)C(=O)/C1=C\\c1ccco1",
        "known_ki_nm": 2100.0,
    },
    {
        "id": "MG132",
        "name": "MG-132",
        "smiles": "CC(C)C[C@@H](NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](CC(C)C)NC(=O)OCc1ccccc1)C=O",
        "known_ki_nm": 42.0,
    },
    {
        "id": "calpainInhII",
        "name": "Calpain Inhibitor II",
        "smiles": "CC(C)C[C@@H](NC(=O)c1ccccn1)C(=O)N[C@@H](CC(C)C)C=O",
        "known_ki_nm": 97.0,
    },
    {
        "id": "leupeptin",
        "name": "Leupeptin",
        "smiles": "CC(C)C[C@@H](NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](CCCNC(=N)N)NC(=O)C)C=O",
        "known_ki_nm": 180.0,
    },
    {
        "id": "cinanserin",
        "name": "Cinanserin",
        "smiles": "CN(C)CCSC(=O)/C=C/c1ccccc1",
        "known_ki_nm": 12500.0,
    },
    {
        "id": "oxytetracycline",
        "name": "Oxytetracycline",
        "smiles": "C[C@@]1(O)[C@H]2C[C@H]3[C@@H](N(C)C)C(=O)C(C(N)=O)=C(O)[C@@]3(O)C(=O)C2=C(O)c2cccc(O)c21",
        "known_ki_nm": 24500.0,
    },
    {
        "id": "bazedoxifene",
        "name": "Bazedoxifene",
        "smiles": "Oc1ccc(/C(=C/2CCN(C)CC2)c2ccc(O)cc2)cc1",
        "known_ki_nm": 8900.0,
    },
    {
        "id": "chloroquine",
        "name": "Chloroquine",
        "smiles": "CCN(CC)CCCC(C)Nc1ccnc2cc(Cl)ccc12",
        "known_ki_nm": 28900.0,
    },
    {
        "id": "luteolin",
        "name": "Luteolin",
        "smiles": "OC1=CC(=C2OC(c3ccc(O)c(O)c3)=CC2=O)C=C(O)C1",
        "known_ki_nm": 5200.0,
    },
    {
        "id": "baicalein",
        "name": "Baicalein",
        "smiles": "O=c1cc(-c2ccccc2)oc2cc(O)c(O)c(O)c12",
        "known_ki_nm": 940.0,
    },
]
